// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// min_in_vector
double min_in_vector(Rcpp::NumericVector input);
RcppExport SEXP _vectorAnalysis_min_in_vector(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(min_in_vector(input));
    return rcpp_result_gen;
END_RCPP
}
// max_in_vector
double max_in_vector(Rcpp::NumericVector input);
RcppExport SEXP _vectorAnalysis_max_in_vector(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(max_in_vector(input));
    return rcpp_result_gen;
END_RCPP
}
// get_outliers_vector
Rcpp::NumericVector get_outliers_vector(Rcpp::NumericVector data);
RcppExport SEXP _vectorAnalysis_get_outliers_vector(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(get_outliers_vector(data));
    return rcpp_result_gen;
END_RCPP
}
// remove_outliers_vector
Rcpp::NumericVector remove_outliers_vector(Rcpp::NumericVector data);
RcppExport SEXP _vectorAnalysis_remove_outliers_vector(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(remove_outliers_vector(data));
    return rcpp_result_gen;
END_RCPP
}
// min_max_normalize
Rcpp::NumericVector min_max_normalize(Rcpp::NumericVector data, Rcpp::NumericVector newMin_newMax);
RcppExport SEXP _vectorAnalysis_min_max_normalize(SEXP dataSEXP, SEXP newMin_newMaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type newMin_newMax(newMin_newMaxSEXP);
    rcpp_result_gen = Rcpp::wrap(min_max_normalize(data, newMin_newMax));
    return rcpp_result_gen;
END_RCPP
}
// z_score_normalize
Rcpp::NumericVector z_score_normalize(Rcpp::NumericVector data);
RcppExport SEXP _vectorAnalysis_z_score_normalize(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(z_score_normalize(data));
    return rcpp_result_gen;
END_RCPP
}
// decimal_normalize
Rcpp::NumericVector decimal_normalize(Rcpp::NumericVector data);
RcppExport SEXP _vectorAnalysis_decimal_normalize(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(decimal_normalize(data));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_vectorAnalysis_min_in_vector", (DL_FUNC) &_vectorAnalysis_min_in_vector, 1},
    {"_vectorAnalysis_max_in_vector", (DL_FUNC) &_vectorAnalysis_max_in_vector, 1},
    {"_vectorAnalysis_get_outliers_vector", (DL_FUNC) &_vectorAnalysis_get_outliers_vector, 1},
    {"_vectorAnalysis_remove_outliers_vector", (DL_FUNC) &_vectorAnalysis_remove_outliers_vector, 1},
    {"_vectorAnalysis_min_max_normalize", (DL_FUNC) &_vectorAnalysis_min_max_normalize, 2},
    {"_vectorAnalysis_z_score_normalize", (DL_FUNC) &_vectorAnalysis_z_score_normalize, 1},
    {"_vectorAnalysis_decimal_normalize", (DL_FUNC) &_vectorAnalysis_decimal_normalize, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_vectorAnalysis(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
