# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

min_in_vector <- function(input) {
    .Call(`_vectorAnalysis_min_in_vector`, input)
}

max_in_vector <- function(input) {
    .Call(`_vectorAnalysis_max_in_vector`, input)
}

get_outliers_vector <- function(data) {
    .Call(`_vectorAnalysis_get_outliers_vector`, data)
}

remove_outliers_vector <- function(data) {
    .Call(`_vectorAnalysis_remove_outliers_vector`, data)
}

min_max_normalize <- function(data, newMin_newMax) {
    .Call(`_vectorAnalysis_min_max_normalize`, data, newMin_newMax)
}

z_score_normalize <- function(data) {
    .Call(`_vectorAnalysis_z_score_normalize`, data)
}

decimal_normalize <- function(data) {
    .Call(`_vectorAnalysis_decimal_normalize`, data)
}

